services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:   
    volumes:
        - mongodb_data_container:/data/db
  server:
    build:
      context: .
      target: final
    depends_on:
     - mongo
    ports:
      - 5001:8080

volumes:
  mongodb_data_container: